#!/usr/bin/env node
/**
 * Generates apps/web/src/app/icons.ts from the iconsax package data.
 *
 * The iconsax web-component fetches manifest.json + per-category JSON via
 * `fetch(new URL("./...", import.meta.url))`, which breaks when the package is
 * bundled by Next.js (the JSON files are never copied next to the chunk).
 *
 * This script extracts just the icons we use (linear style) into a self-
 * contained TS module, so the app has zero runtime network/fetch dependency.
 *
 * Run:  node scripts/generate-icons.mjs
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Resolve the real (symlink-followed) iconsax dist dir.
const iconsaxEntry = require.resolve("iconsax", { paths: [resolve(__dirname, "../apps/web")] });
const distDir = dirname(iconsaxEntry);

// Icons we reference in the app (name -> icon file reference).
const ICONS = [
  "chart-2", // Analytics
  "hierarchy", // Funnels
  "weight", // Comparison
  "flash", // Events
  "link", // Projects
  "global", // Domains
  "magic-star", // Usage
  "arrow-right-01", // Usage chevron
  "logout-01", // Sign out
  "arrow-down-01", // Project switcher
  "refresh-right", // Refresh
  "grid-2", // Columns toggle
  "filter-square", // Filters
  "calendar-2", // Date picker
  "setting-2", // Settings sub-nav: General
  "card-pos", // Settings sub-nav: Billing
  "key-square", // Settings sub-nav: API Keys
  "monitor-mobile", // Settings sub-nav: Tracking
  "export-arrow-01", // Settings sub-nav: Webhooks
  "close-circle", // Close / remove
];

const manifest = JSON.parse(
  readFileSync(resolve(distDir, "manifest.json"), "utf-8"),
);

const style = "linear";
const out = {};

for (const name of ICONS) {
  const meta = manifest[name];
  if (!meta) {
    console.warn(`⚠️  iconsax: "${name}" not in manifest — skipping`);
    continue;
  }
  const data = JSON.parse(
    readFileSync(resolve(distDir, "data", `${meta.category}.json`), "utf-8"),
  );
  const svg = data[name]?.[style];
  if (!svg) {
    console.warn(`⚠️  iconsax: "${name}" has no ${style} style — skipping`);
    continue;
  }
  out[name] = svg;
}

const file = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.\n// Icon SVGs (linear style) extracted from the "iconsax" package (MIT).\n\nexport const ICONS: Record<string, string> = ${JSON.stringify(out, null, 2)};\n`;

const target = resolve(__dirname, "../apps/web/src/app/icons.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, file);

console.log(`✅ Wrote ${Object.keys(out).length} icons to ${target}`);
for (const name of Object.keys(out)) {
  console.log(`   - ${name}`);
}
