import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createApp } from "../src/app";
import { MemoryRepo } from "../src/repositories/memory";
import { configFromEnv } from "../src/config";

const here = dirname(fileURLToPath(import.meta.url));

describe("SDK serving", () => {
  it("GET /sdk/trell.js serves javascript", async () => {
    const app = createApp({ repo: new MemoryRepo(), config: configFromEnv({} as NodeJS.ProcessEnv) });
    const res = await app.request("/sdk/trell.js");
    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toContain("application/javascript");
    const body = await res.text();
    expect(body.length).toBeGreaterThan(1000);
    expect(body).toContain("trell");
  });

  it("serves the minified build when present", async () => {
    const src = readFileSync(join(here, "../public/trell.js"), "utf-8");
    const app = createApp({ repo: new MemoryRepo(), config: configFromEnv({} as NodeJS.ProcessEnv) });
    const res = await app.request("/sdk/trell.js");
    const body = await res.text();
    // trell.min.js is generated by `pnpm build:sdk`; the served bundle must not
    // be larger than the readable source.
    expect(body.length).toBeLessThanOrEqual(src.length);
  });
});
